[package]
name = "p2pclient"
version = "0.1.0"
authors = ["ramones156 <ramonvansprundel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
